import {it,expect,vi} from 'vitest';
import {NullEngine,Scene,StandardMaterial,Texture,Vector2,Vector3,VertexBuffer} from '@babylonjs/core';
import GlobeSet from '../src/GlobeSet';
import {TerrainTransition} from '../examples-npm/globe-mode/src/TerrainTransition';
import RasterOSM from '../src/raster/RasterOSM';
import {globeLODPlan} from '../examples-npm/globe-mode/src/GlobeLODPlan';
vi.mock('../src/core/Attribution',()=>({default:class {advancedTexture={};addAttribution(){}}}));
it.each([true, false])('keeps terrain fallback safe while Google mode %s resizes and repositions its regional window', google => {
 const engine=new NullEngine(),scene=new Scene(engine);
 const globe=new GlobeSet(scene,engine,{radius:60,attribution:false,backingSurface:false});
 const before=globeLODPlan(17,!google)[1],after=globeLODPlan(17,google)[1];
 // The LOD window dimensions and zooms trigger the production resize path;
 // two terrain segments are enough to exercise its geometry lifecycle.
 globe.createGeometry(new Vector2(before.size,before.size),20,2);
 globe.updateRaster(40.7484,-73.9857,before.zoom);
 const tile=globe.ourTiles[Math.floor(globe.ourTiles.length/2)];
 tile.terrainLoaded=true;tile.mesh.setEnabled(true);
 const material=new StandardMaterial('ready regional terrain',scene),texture=new Texture(null,scene);
 vi.spyOn(texture,'isReady').mockReturnValue(true);
 material.diffuseTexture=texture;tile.mesh.material=material;tile.material=material;
 const transition=new TerrainTransition();
 transition.capture(globe,after.zoom,40.7484,-73.9857,true);
 const fallback=scene.getMeshByName('previous terrain')!;
 expect(fallback).toBeDefined();
 globe.createGeometry(new Vector2(after.size,after.size),20,2);
 expect(globe.ourTiles.every(tile=>tile.tileCoords===undefined)).toBe(true);
 expect.soft(()=>transition.capture(globe,after.zoom,40.7484,-73.9857)).not.toThrow();
 expect.soft(()=>transition.capture(globe,after.zoom,40.7484,-73.9857,true)).not.toThrow();
 expect.soft(()=>transition.update(1000)).not.toThrow();
 expect(fallback.isDisposed()).toBe(false);
 globe.updateRaster(40.7484,-73.9857,after.zoom);
 expect(()=>transition.update(1300)).not.toThrow();
 expect(fallback.isDisposed()).toBe(false);
 expect(fallback.isEnabled()).toBe(true);
 transition.dispose();scene.dispose();engine.dispose();
});

it('retains independent terrain geometry until matching replacement imagery and elevation are ready',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 const globe=new GlobeSet(scene,engine,{radius:60,attribution:false,backingSurface:false});
 globe.createGeometry(new Vector2(1,1),20,2);globe.updateRaster(0,0,17);
 const tile=globe.ourTiles[0];tile.terrainLoaded=true;
 const material=new StandardMaterial('terrain',scene);const texture=new Texture(null,scene);
 const disposed=vi.spyOn(texture,'dispose');
 vi.spyOn(texture,'isReady').mockReturnValue(true);material.diffuseTexture=texture;tile.mesh.material=material;
 tile.mesh.setEnabled(true);
 const originalGeometry=tile.mesh.geometry;
 const transition=new TerrainTransition();transition.capture(globe as any,16);
 const snapshot=scene.meshes.find(mesh=>mesh.name==='previous terrain')!;
 expect(snapshot).toBeDefined();expect(snapshot.geometry).not.toBe(tile.mesh.geometry);
 expect(snapshot.geometry).toBe(originalGeometry);
 expect(tile.mesh.geometry).toBeNull();
 expect(snapshot.material).toBe(material);
 expect(snapshot.renderingGroupId).toBe(Math.min(8,tile.mesh.renderingGroupId+1));
 expect(tile.material).toBeUndefined();
 expect(disposed).not.toHaveBeenCalled();
 expect(snapshot.material?.isFrozen).toBe(true);
 expect(scene.blockMaterialDirtyMechanism).toBe(false);
 const positions=Array.from(snapshot.getVerticesData(VertexBuffer.PositionKind)!);
 globe.updateRaster(0,0,16);tile.terrainLoaded=false;
 expect(tile.mesh.geometry).not.toBe(originalGeometry);
 expect(tile.material).not.toBe(material);
 expect(disposed).not.toHaveBeenCalled();
 transition.update(1000);expect(snapshot.isDisposed()).toBe(false);
 expect(Array.from(snapshot.getVerticesData(VertexBuffer.PositionKind)!)).toEqual(positions);
 tile.terrainLoaded=true;
 const replacement=tile.material!;
 const replacementTexture=new Texture(null,scene);
 const replacementDisposed=vi.spyOn(replacementTexture,'dispose');
 vi.spyOn(replacementTexture,'isReady').mockReturnValue(true);
 replacement.diffuseTexture=replacementTexture;
 transition.update(1300);expect(snapshot.isDisposed()).toBe(false);
 tile.mesh.setEnabled(true);
 tile.mesh.isVisible=false;
 transition.update(1600);expect(snapshot.isDisposed()).toBe(false);
 tile.mesh.isVisible=true;
 tile.mesh.visibility=0;
 transition.update(1900);expect(snapshot.isDisposed()).toBe(false);
 tile.mesh.visibility=1;
 const geometryReady=vi.spyOn(globe,'isTileGeometryReady').mockReturnValue(false);
 transition.update(2200);expect(snapshot.isDisposed()).toBe(false);
 geometryReady.mockRestore();
 transition.update(2500);expect(snapshot.isDisposed()).toBe(true);
 expect(disposed).toHaveBeenCalledOnce();
 expect(tile.mesh.material).toBe(replacement);
 expect(replacementDisposed).not.toHaveBeenCalled();
 transition.dispose();scene.dispose();engine.dispose();
});

it('retains terrain during a same-zoom tile-window move',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 const globe=new GlobeSet(scene,engine,{radius:60,attribution:false,backingSurface:false});
 globe.createGeometry(new Vector2(3,3),20,2);globe.updateRaster(40.7484,-73.9857,14);
 const tile=globe.ourTiles[0];tile.terrainLoaded=true;
 const material=new StandardMaterial('terrain',scene),texture=new Texture(null,scene);
 vi.spyOn(texture,'isReady').mockReturnValue(true);material.diffuseTexture=texture;tile.mesh.material=material;
 tile.mesh.setEnabled(true);
 const longitude=globe.ourTileMath.tile_to_lon(globe.ourTiles[0].tileCoords.x+2.5,14);
 const transition=new TerrainTransition();transition.capture(globe,14,40.7484,longitude);
 globe.updateRaster(40.7484,longitude,14);
 transition.update(1);
 const retained=scene.meshes.find(mesh=>mesh.name==='previous terrain')!;
 expect(retained.isDisposed()).toBe(false);
 vi.spyOn(scene,'frustumPlanes','get').mockReturnValue([]);vi.spyOn(retained,'isInFrustum').mockReturnValue(false);
 transition.update(300);expect(retained.isDisposed()).toBe(true);
 transition.dispose();scene.dispose();engine.dispose();
});

it('retains visible imagery while its DEM is still loading',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 const globe=new GlobeSet(scene,engine,{radius:60,attribution:false,backingSurface:false});
 globe.createGeometry(new Vector2(1,1),20,2);globe.updateRaster(40.7484,-73.9857,14);
 const tile=globe.ourTiles[0];tile.terrainLoaded=false;
 const material=new StandardMaterial('ready imagery',scene),texture=new Texture(null,scene);
 vi.spyOn(texture,'isReady').mockReturnValue(true);material.diffuseTexture=texture;tile.mesh.material=material;
 tile.mesh.setEnabled(true);
 const transition=new TerrainTransition();transition.capture(globe,15);
 const retained=scene.getMeshByName('previous terrain');
 expect(retained).toBeDefined();
 globe.updateRaster(40.7484,-73.9857,15);
 transition.update(1);
 expect(retained!.isDisposed()).toBe(false);
 expect(retained!.isEnabled()).toBe(true);
 transition.dispose();scene.dispose();engine.dispose();
});

it('does not promote a hidden flat tile into a visible terrain fallback',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 const globe=new GlobeSet(scene,engine,{radius:60,attribution:false,backingSurface:false});
 globe.createGeometry(new Vector2(1,1),20,2);globe.updateRaster(40.7484,-73.9857,14);
 globe.setTerrainDisplayRequirement(true);
 const tile=globe.ourTiles[0];
 const material=new StandardMaterial('ready imagery',scene),texture=new Texture(null,scene);
 vi.spyOn(texture,'isReady').mockReturnValue(true);material.diffuseTexture=texture;tile.mesh.material=material;
 expect(tile.mesh.isEnabled()).toBe(false);
 const transition=new TerrainTransition();transition.capture(globe,15);
 expect(scene.getMeshByName('previous terrain')).toBeNull();
 transition.dispose();scene.dispose();engine.dispose();
});

it('does not capture an enabled raster before its required DEM is ready',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 const globe=new GlobeSet(scene,engine,{radius:60,attribution:false,backingSurface:false});
 globe.createGeometry(new Vector2(1,1),20,2);globe.updateRaster(40.7484,-73.9857,14);
 globe.setTerrainDisplayRequirement(true);
 const tile=globe.ourTiles[0];tile.terrainLoaded=false;
 const material=new StandardMaterial('ready image only',scene),texture=new Texture(null,scene);
 vi.spyOn(texture,'isReady').mockReturnValue(true);
 material.diffuseTexture=texture;tile.mesh.material=material;tile.material=material;
 tile.mesh.setEnabled(true);
 expect(globe.isTileDisplayReady(tile)).toBe(false);
 const transition=new TerrainTransition();transition.capture(globe,15);
 expect(scene.getMeshByName('previous terrain')).toBeNull();
 transition.dispose();scene.dispose();engine.dispose();
});

it('does not discard visible fallback terrain when fast movement crosses more than two windows',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 const globe=new GlobeSet(scene,engine,{radius:60,attribution:false,backingSurface:false});
 globe.createGeometry(new Vector2(1,1),20,2);globe.updateRaster(40.7484,-73.9857,14);
 const firstX=globe.ourTiles[0].tileCoords.x;
 const transition=new TerrainTransition();
 const retained=[];
 for(let step=1;step<=3;step++){
  const tile=globe.ourTiles[0];tile.terrainLoaded=true;
  const material=new StandardMaterial(`terrain ${step}`,scene),texture=new Texture(null,scene);
  vi.spyOn(texture,'isReady').mockReturnValue(true);material.diffuseTexture=texture;tile.mesh.material=material;
  tile.mesh.setEnabled(true);
  const longitude=globe.ourTileMath.tile_to_lon(firstX+step+0.5,14);
  transition.capture(globe,14,40.7484,longitude);
  retained.push(scene.meshes.filter(mesh=>mesh.name==='previous terrain').at(-1)!);
  globe.updateRaster(40.7484,longitude,14);
 }
 expect(retained).toHaveLength(3);
 expect(retained.every(mesh=>mesh && !mesh.isDisposed())).toBe(true);
 transition.dispose();scene.dispose();engine.dispose();
});

it('holds ready imagery through a basemap change at the same tile coordinates',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 const globe=new GlobeSet(scene,engine,{radius:60,attribution:false,backingSurface:false});
 globe.createGeometry(new Vector2(1,1),20,2);globe.updateRaster(40.7484,-73.9857,14);
 const tile=globe.ourTiles[0];tile.terrainLoaded=true;tile.mesh.setEnabled(true);
 const oldMaterial=new StandardMaterial('old style',scene),oldTexture=new Texture(null,scene);
 vi.spyOn(oldTexture,'isReady').mockReturnValue(true);oldMaterial.diffuseTexture=oldTexture;tile.mesh.material=oldMaterial;tile.material=oldMaterial;
 const coordinate=tile.tileCoords.clone();
 const geometry=tile.mesh.geometry;
 const transition=new TerrainTransition();transition.capture(globe,14,undefined,undefined,true);
 const retained=scene.getMeshByName('previous terrain')!;
 expect(retained.isDisposed()).toBe(false);
 expect(tile.mesh.geometry).toBe(geometry);
 globe.setRasterProvider(new RasterOSM(globe));
 globe.updateRaster(40.7484,-73.9857,14);
 expect(tile.tileCoords.equals(coordinate)).toBe(true);
 expect(tile.mesh.geometry).toBe(geometry);
 transition.update(500);
 expect(retained.isDisposed()).toBe(false);
 tile.terrainLoaded=true;
 const newTexture=new Texture(null,scene);
 vi.spyOn(newTexture,'isReady').mockReturnValue(true);tile.material!.diffuseTexture=newTexture;
 transition.update(1000);
 expect(retained.isDisposed()).toBe(false);
 tile.mesh.setEnabled(true);
 transition.update(1300);
 expect(retained.isDisposed()).toBe(true);
 transition.dispose();scene.dispose();engine.dispose();
});

it('retires a terrain-free fallback once replacement imagery is drawable',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 const globe=new GlobeSet(scene,engine,{radius:60,attribution:false,backingSurface:false});
 globe.createGeometry(new Vector2(1,1),20,2);globe.updateRaster(40.7484,-73.9857,14);
 globe.setTerrainDisplayRequirement(false);
 const tile=globe.ourTiles[0];tile.terrainLoaded=false;tile.mesh.setEnabled(true);
 const oldMaterial=new StandardMaterial('old style',scene),oldTexture=new Texture(null,scene);
 vi.spyOn(oldTexture,'isReady').mockReturnValue(true);
 oldMaterial.diffuseTexture=oldTexture;tile.mesh.material=oldMaterial;tile.material=oldMaterial;
 const transition=new TerrainTransition();transition.capture(globe,14,undefined,undefined,true);
 const fallback=scene.getMeshByName('previous terrain')!;
 expect(fallback).toBeDefined();
 globe.setRasterProvider(new RasterOSM(globe));
 globe.updateRaster(40.7484,-73.9857,14);
 const newTexture=new Texture(null,scene);
 vi.spyOn(newTexture,'isReady').mockReturnValue(true);
 tile.material!.diffuseTexture=newTexture;
 tile.mesh.setEnabled(true);
 expect(globe.isTileDisplayReady(tile)).toBe(true);
 transition.update(1000);
 expect(fallback.isDisposed()).toBe(true);
 transition.dispose();scene.dispose();engine.dispose();
});

it('keeps the latest drawable style during repeated raster changes',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 const globe=new GlobeSet(scene,engine,{radius:60,attribution:false,backingSurface:false});
 globe.createGeometry(new Vector2(1,1),20,2);globe.updateRaster(40.7484,-73.9857,14);
 const tile=globe.ourTiles[0];tile.terrainLoaded=true;tile.mesh.setEnabled(true);
 const makeMaterial=(name:string)=>{
  const material=new StandardMaterial(name,scene),texture=new Texture(null,scene);
  vi.spyOn(texture,'isReady').mockReturnValue(true);material.diffuseTexture=texture;
  return material;
 };
 const first=makeMaterial('first');tile.mesh.material=first;tile.material=first;
 const transition=new TerrainTransition();transition.capture(globe,14,undefined,undefined,true);
 const firstFallback=scene.getMeshByName('previous terrain')!;
 globe.setRasterProvider(new RasterOSM(globe));globe.updateRaster(40.7484,-73.9857,14);
 const second=tile.material!;const secondTexture=new Texture(null,scene);
 vi.spyOn(secondTexture,'isReady').mockReturnValue(true);second.diffuseTexture=secondTexture;
 tile.mesh.setEnabled(true);
 transition.capture(globe,14,undefined,undefined,true);
 const fallbacks=scene.meshes.filter(mesh=>mesh.name==='previous terrain' && !mesh.isDisposed());
 expect(firstFallback.isDisposed()).toBe(true);
 expect(fallbacks).toHaveLength(1);
 expect(fallbacks[0].material).toBe(second);
 transition.dispose();scene.dispose();engine.dispose();
});

it('keeps raster fallback when a same-zoom regional window grows',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 const globe=new GlobeSet(scene,engine,{radius:60,attribution:false,backingSurface:false});
 globe.createGeometry(new Vector2(1,1),20,2);globe.updateRaster(40.7484,-73.9857,12);
 const tile=globe.ourTiles[0];tile.terrainLoaded=true;
 const material=new StandardMaterial('ready map',scene),texture=new Texture(null,scene);
 vi.spyOn(texture,'isReady').mockReturnValue(true);material.diffuseTexture=texture;tile.mesh.material=material;
 tile.mesh.setEnabled(true);
 const transition=new TerrainTransition();transition.capture(globe,12,40.7484,-73.9857,true);
 globe.createGeometry(new Vector2(2,2),20,2);globe.updateRaster(40.7484,-73.9857,12);
 transition.update(1);
 const retained=scene.getMeshByName('previous terrain')!;
 expect(retained.isDisposed()).toBe(false);
 expect(retained.isEnabled()).toBe(true);
 transition.dispose();scene.dispose();engine.dispose();
});
