import {it,expect,vi} from 'vitest';
import {NullEngine,Scene,StandardMaterial,Texture,Vector2,Vector3,VertexBuffer} from '@babylonjs/core';
import GlobeSet from '../src/GlobeSet';
import {TerrainTransition} from '../examples-npm/globe-mode/src/TerrainTransition';
import RasterOSM from '../src/raster/RasterOSM';
vi.mock('../src/core/Attribution',()=>({default:class {advancedTexture={};addAttribution(){}}}));
it('retains independent terrain geometry until matching replacement imagery and elevation are ready',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 const globe=new GlobeSet(scene,engine,{radius:60,attribution:false,backingSurface:false});
 globe.createGeometry(new Vector2(1,1),20,2);globe.updateRaster(0,0,17);
 const tile=globe.ourTiles[0];tile.terrainLoaded=true;
 const material=new StandardMaterial('terrain',scene);const texture=new Texture(null,scene);
 const disposed=vi.spyOn(texture,'dispose');
 vi.spyOn(texture,'isReady').mockReturnValue(true);material.diffuseTexture=texture;tile.mesh.material=material;
 const originalGeometry=tile.mesh.geometry;
 const transition=new TerrainTransition();transition.capture(globe as any,16);
 const snapshot=scene.meshes.find(mesh=>mesh.name==='previous terrain')!;
 expect(snapshot).toBeDefined();expect(snapshot.geometry).not.toBe(tile.mesh.geometry);
 expect(snapshot.geometry).toBe(originalGeometry);
 expect(tile.mesh.geometry).toBeNull();
 expect(snapshot.material).toBe(material);
 expect(snapshot.renderingGroupId).toBe(Math.min(7,tile.mesh.renderingGroupId+1));
 expect(tile.material).toBeUndefined();
 expect(disposed).not.toHaveBeenCalled();
 expect(snapshot.material?.isFrozen).toBe(true);
 expect(scene.blockMaterialDirtyMechanism).toBe(false);
 const positions=Array.from(snapshot.getVerticesData(VertexBuffer.PositionKind)!);
 globe.updateRaster(0,0,16);tile.terrainLoaded=false;
 expect(tile.mesh.geometry).not.toBe(originalGeometry);
 expect(tile.material).not.toBe(material);
 expect(disposed).not.toHaveBeenCalled();
 transition.update(1000);expect(snapshot.isDisposed()).toBe(false);
 expect(Array.from(snapshot.getVerticesData(VertexBuffer.PositionKind)!)).toEqual(positions);
 tile.terrainLoaded=true;
 const replacement=tile.material!;
 const replacementTexture=new Texture(null,scene);
 const replacementDisposed=vi.spyOn(replacementTexture,'dispose');
 vi.spyOn(replacementTexture,'isReady').mockReturnValue(true);
 replacement.diffuseTexture=replacementTexture;
 transition.update(1300);expect(snapshot.isDisposed()).toBe(true);
 expect(disposed).toHaveBeenCalledOnce();
 expect(tile.mesh.material).toBe(replacement);
 expect(replacementDisposed).not.toHaveBeenCalled();
 transition.dispose();scene.dispose();engine.dispose();
});

it('retains terrain during a same-zoom tile-window move',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 const globe=new GlobeSet(scene,engine,{radius:60,attribution:false,backingSurface:false});
 globe.createGeometry(new Vector2(3,3),20,2);globe.updateRaster(40.7484,-73.9857,14);
 const tile=globe.ourTiles[0];tile.terrainLoaded=true;
 const material=new StandardMaterial('terrain',scene),texture=new Texture(null,scene);
 vi.spyOn(texture,'isReady').mockReturnValue(true);material.diffuseTexture=texture;tile.mesh.material=material;
 const longitude=globe.ourTileMath.tile_to_lon(globe.ourTiles[0].tileCoords.x+2.5,14);
 const transition=new TerrainTransition();transition.capture(globe,14,40.7484,longitude);
 globe.updateRaster(40.7484,longitude,14);
 transition.update(1);
 const retained=scene.meshes.find(mesh=>mesh.name==='previous terrain')!;
 expect(retained.isDisposed()).toBe(false);
 vi.spyOn(scene,'frustumPlanes','get').mockReturnValue([]);vi.spyOn(retained,'isInFrustum').mockReturnValue(false);
 transition.update(300);expect(retained.isDisposed()).toBe(true);
 transition.dispose();scene.dispose();engine.dispose();
});

it('does not discard visible fallback terrain when fast movement crosses more than two windows',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 const globe=new GlobeSet(scene,engine,{radius:60,attribution:false,backingSurface:false});
 globe.createGeometry(new Vector2(1,1),20,2);globe.updateRaster(40.7484,-73.9857,14);
 const firstX=globe.ourTiles[0].tileCoords.x;
 const transition=new TerrainTransition();
 const retained=[];
 for(let step=1;step<=3;step++){
  const tile=globe.ourTiles[0];tile.terrainLoaded=true;
  const material=new StandardMaterial(`terrain ${step}`,scene),texture=new Texture(null,scene);
  vi.spyOn(texture,'isReady').mockReturnValue(true);material.diffuseTexture=texture;tile.mesh.material=material;
  const longitude=globe.ourTileMath.tile_to_lon(firstX+step+0.5,14);
  transition.capture(globe,14,40.7484,longitude);
  retained.push(scene.meshes.filter(mesh=>mesh.name==='previous terrain').at(-1)!);
  globe.updateRaster(40.7484,longitude,14);
 }
 expect(retained).toHaveLength(3);
 expect(retained.every(mesh=>mesh && !mesh.isDisposed())).toBe(true);
 transition.dispose();scene.dispose();engine.dispose();
});

it('holds ready imagery through a basemap change at the same tile coordinates',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 const globe=new GlobeSet(scene,engine,{radius:60,attribution:false,backingSurface:false});
 globe.createGeometry(new Vector2(1,1),20,2);globe.updateRaster(40.7484,-73.9857,14);
 const tile=globe.ourTiles[0];tile.terrainLoaded=true;tile.mesh.setEnabled(true);
 const oldMaterial=new StandardMaterial('old style',scene),oldTexture=new Texture(null,scene);
 vi.spyOn(oldTexture,'isReady').mockReturnValue(true);oldMaterial.diffuseTexture=oldTexture;tile.mesh.material=oldMaterial;tile.material=oldMaterial;
 const coordinate=tile.tileCoords.clone();
 const transition=new TerrainTransition();transition.capture(globe,14,undefined,undefined,true);
 const retained=scene.getMeshByName('previous terrain')!;
 expect(retained.isDisposed()).toBe(false);
 globe.setRasterProvider(new RasterOSM(globe));
 globe.updateRaster(40.7484,-73.9857,14);
 expect(tile.tileCoords.equals(coordinate)).toBe(true);
 transition.update(500);
 expect(retained.isDisposed()).toBe(false);
 tile.terrainLoaded=true;
 const newTexture=new Texture(null,scene);
 vi.spyOn(newTexture,'isReady').mockReturnValue(true);tile.material!.diffuseTexture=newTexture;
 transition.update(1000);
 expect(retained.isDisposed()).toBe(true);
 transition.dispose();scene.dispose();engine.dispose();
});
