import { expect, it, vi } from "vitest";
import { NullEngine } from "@babylonjs/core/Engines/nullEngine.js";
import { Scene } from "@babylonjs/core/scene.js";
import { FreeCamera } from "@babylonjs/core/Cameras/freeCamera.js";
import { Vector3 } from "@babylonjs/core/Maths/math.vector.js";
import { MeshBuilder } from "@babylonjs/core/Meshes/meshBuilder.js";
import { StandardMaterial } from "@babylonjs/core/Materials/standardMaterial.js";
import { RawTexture } from "@babylonjs/core/Materials/Textures/rawTexture.js";
import { TileRasterMaterial } from "../src/core/TileRasterMaterial.js";

it("updates raster shader state without scanning unrelated scene meshes", async () => {
    const engine = new NullEngine();
    const scene = new Scene(engine);
    new FreeCamera("camera", Vector3.Zero(), scene);
    const tile = MeshBuilder.CreateBox("tile", {}, scene);
    tile.position.z = 10;
    const other = MeshBuilder.CreateBox("other", {}, scene);
    other.position.z = 10;
    const lod = MeshBuilder.CreateBox("tile LOD", {}, scene);
    lod.position.set(2, 0, 10);
    const material = new TileRasterMaterial("raster", scene);
    const ordinary = new StandardMaterial("ordinary", scene);
    tile.material = material;
    lod.material = material;
    other.material = ordinary;
    await scene.whenReadyAsync();
    scene.render();
    const iterator = vi.spyOn(scene.meshes, Symbol.iterator);
    const texture = RawTexture.CreateRGBATexture(new Uint8Array(16), 2, 2, scene);
    material.freeze();
    material.unfreeze();
    material.diffuseTexture = texture;
    expect(iterator).not.toHaveBeenCalled();
    expect(tile.subMeshes[0].materialDefines?.isDirty).toBe(true);
    expect(lod.subMeshes[0].materialDefines?.isDirty).toBe(true);
    expect(other.subMeshes[0].materialDefines?.isDirty).toBe(false);
    iterator.mockRestore();
    texture.getInternalTexture()!.isReady = true;
    await scene.whenReadyAsync();
    scene.render();
    expect(tile.subMeshes[0].materialDefines?.isDirty).toBe(false);
    expect(lod.subMeshes[0].materialDefines?.isDirty).toBe(false);
    scene.dispose(); engine.dispose();
});
