import { Scene } from "@babylonjs/core/scene";
import { Vector2 } from "@babylonjs/core/Maths/math";
import { Mesh } from "@babylonjs/core/Meshes/mesh";
export default class TileSet {
    private totalWidthMeters;
    meshPrecision: number;
    private scene;
    private tileWidth;
    private xmin;
    private zmin;
    private xmax;
    private zmax;
    private globalMinHeight;
    private ourTiles;
    private exaggeration;
    private subdivisions;
    private zoom;
    private tileCorner;
    private centerCoords;
    private rasterProvider;
    private accessToken;
    private osmBuildings;
    private ourMB;
    constructor(subdivisions: number, totalWidthMeters: number, meshPrecision: number, scene: Scene);
    makeSingleTileMesh(x: number, y: number, precision: number): Mesh;
    setRasterProvider(providerName: string, accessToken?: string): void;
    lon2tile(lon: number, zoom: number): number;
    lat2tile(lat: number, zoom: number): number;
    lon2tileExact(lon: number, zoom: number): number;
    lat2tileExact(lat: number, zoom: number): number;
    getTileFromLatLon(coordinates: Vector2, zoom: number): Vector2;
    computeCornerTile(coordinates: Vector2, zoom: number): Vector2;
    computeTiletotalWidthMeters(coordinates: Vector2, zoom: number): number;
    computeTileScale(): number;
    GetWorldPosition(coordinates: Vector2): Vector2;
    updateRaster(centerCoords: Vector2, zoom: number): void;
    generateBuildings(exaggeration: number): void;
    updateTerrain(exaggeration: number): Promise<void>;
    setupTerrainLOD(precisions: number[], distances: number[]): void;
}
