import { Vector2 } from "@babylonjs/core/Maths/math.js";
import { Vector3 } from "@babylonjs/core/Maths/math.js";
import { Mesh } from "@babylonjs/core/Meshes/mesh.js";
import { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial.js';
import type TileBuilding from "./TileBuilding.js";
import { BoundingBox } from "@babylonjs/core/Culling/boundingBox.js";
import type TileSet from "./TileSet.js";
export default class Tile {
    mesh: Mesh;
    tileSet: TileSet;
    material: StandardMaterial;
    tileCoords: Vector3;
    box2D: BoundingBox;
    buildings: TileBuilding[];
    mergedBuildingMesh: Mesh | undefined;
    dem: number[];
    demDimensions: Vector2;
    minHeight: number;
    maxHeight: number;
    terrainLoaded: boolean;
    eastSeamFixed: boolean;
    northSeamFixed: boolean;
    northEastSeamFixed: boolean;
    constructor(mesh: Mesh, tileSet: TileSet);
    private makeSphere;
    deleteBuildings(): void;
    hideIndividualBuildings(): void;
    getAllBuildingMeshes(): Mesh[];
    isBuildingInsideTileBoundingBox(m: Mesh): boolean;
}
